const supabase = require('../config/supabaseClient');
const { assumeCustomerRole } = require('../services/awsService');
const { findUnattachedVolumes, findIdleIPs } = require('../services/scannerService');

/**
 * Triggers a scan for a specific cloud account and saves findings to the 'reports' table.
 */
exports.runScan = async (req, res) => {
    try {
        const { cloud_account_id } = req.body;

        // 1. Ensure the user owns this cloud account (Security check)
        const { data: account, error: accountError } = await supabase
            .from('cloud_accounts')
            .select('*')
            .eq('id', cloud_account_id)
            .eq('tenant_id', req.user.user_metadata.tenant_id) // From verifyJWT middleware
            .single();

        if (accountError || !account) {
            return res.status(404).json({ error: 'Cloud account not found or access denied.' });
        }

        // 2. Assume the AWS Role to get temporary guest credentials
        // The DB schema shows credentials_json. We assume the role ARN is stored inside it.
        const roleArn = account.credentials_json?.role_arn;
        if (!roleArn) {
            return res.status(400).json({ error: 'No IAM Role ARN found in credentials_json for this account.' });
        }

        console.log(`Assuming role for ${roleArn}...`);
        const credentials = await assumeCustomerRole(roleArn);

        // 3. Run the Scanners
        console.log('Running Zombie Scanners...');
        const unattachedVolumes = await findUnattachedVolumes(credentials, account.region || 'us-east-1');
        const idleIPs = await findIdleIPs(credentials, account.region || 'us-east-1');

        // Calculate total savings using the new property names matching the DB
        const totalVolumeSavings = unattachedVolumes.reduce((sum, vol) => sum + vol.estimated_monthly_cost, 0);
        const totalIpSavings = idleIPs.reduce((sum, ip) => sum + ip.estimated_monthly_cost, 0);
        const totalSavings = totalVolumeSavings + totalIpSavings;

        // 4. Save the results to Supabase `zombie_resources` table
        // We append the tenant_id and account_id to the exact payload generated by the scanners
        const allZombies = [...unattachedVolumes, ...idleIPs].map(zombie => ({
            ...zombie,
            tenant_id: req.user.user_metadata.tenant_id,
            account_id: account.id
        }));

        let insertedCount = 0;

        if (allZombies.length > 0) {
            const { data: insertedZombies, error: insertError } = await supabase
                .from('zombie_resources')
                .insert(allZombies)
                .select();

            if (insertError) throw insertError;
            insertedCount = insertedZombies.length;
        }

        res.status(200).json({
            message: 'Scan completed successfully!',
            zombies_found: insertedCount,
            estimated_monthly_savings_usd: totalSavings,
        });

    } catch (error) {
        console.error('Scan Error:', error);
        res.status(500).json({ error: error.message || 'An error occurred during the scan.' });
    }
};
